// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fcm_cpp
List fcm_cpp(List tokens_list, NumericVector type_widths, LogicalVector keep_types, double window_size, NumericVector weights_vec, int weights_mode, bool include_target, std::string decay_type, double decay_param, bool asymmetric, double forward_weight, double backward_weight, bool verbose);
RcppExport SEXP _wordembeddings_fcm_cpp(SEXP tokens_listSEXP, SEXP type_widthsSEXP, SEXP keep_typesSEXP, SEXP window_sizeSEXP, SEXP weights_vecSEXP, SEXP weights_modeSEXP, SEXP include_targetSEXP, SEXP decay_typeSEXP, SEXP decay_paramSEXP, SEXP asymmetricSEXP, SEXP forward_weightSEXP, SEXP backward_weightSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tokens_list(tokens_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type type_widths(type_widthsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type keep_types(keep_typesSEXP);
    Rcpp::traits::input_parameter< double >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights_vec(weights_vecSEXP);
    Rcpp::traits::input_parameter< int >::type weights_mode(weights_modeSEXP);
    Rcpp::traits::input_parameter< bool >::type include_target(include_targetSEXP);
    Rcpp::traits::input_parameter< std::string >::type decay_type(decay_typeSEXP);
    Rcpp::traits::input_parameter< double >::type decay_param(decay_paramSEXP);
    Rcpp::traits::input_parameter< bool >::type asymmetric(asymmetricSEXP);
    Rcpp::traits::input_parameter< double >::type forward_weight(forward_weightSEXP);
    Rcpp::traits::input_parameter< double >::type backward_weight(backward_weightSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(fcm_cpp(tokens_list, type_widths, keep_types, window_size, weights_vec, weights_mode, include_target, decay_type, decay_param, asymmetric, forward_weight, backward_weight, verbose));
    return rcpp_result_gen;
END_RCPP
}
// sgns_train_cpp
List sgns_train_cpp(const IntegerVector& i_indices, const IntegerVector& j_indices, const NumericVector& x_values, const int n_words, const int n_contexts, const int n_dims, const int n_neg, const double lr, const int n_iterations, const int batch_size, const double smoothing, const bool reject_positives, const std::string init_type, const bool bootstrap_positive, const int seed, const bool verbose);
RcppExport SEXP _wordembeddings_sgns_train_cpp(SEXP i_indicesSEXP, SEXP j_indicesSEXP, SEXP x_valuesSEXP, SEXP n_wordsSEXP, SEXP n_contextsSEXP, SEXP n_dimsSEXP, SEXP n_negSEXP, SEXP lrSEXP, SEXP n_iterationsSEXP, SEXP batch_sizeSEXP, SEXP smoothingSEXP, SEXP reject_positivesSEXP, SEXP init_typeSEXP, SEXP bootstrap_positiveSEXP, SEXP seedSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type i_indices(i_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type j_indices(j_indicesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x_values(x_valuesSEXP);
    Rcpp::traits::input_parameter< const int >::type n_words(n_wordsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_contexts(n_contextsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_dims(n_dimsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_neg(n_negSEXP);
    Rcpp::traits::input_parameter< const double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< const int >::type n_iterations(n_iterationsSEXP);
    Rcpp::traits::input_parameter< const int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< const double >::type smoothing(smoothingSEXP);
    Rcpp::traits::input_parameter< const bool >::type reject_positives(reject_positivesSEXP);
    Rcpp::traits::input_parameter< const std::string >::type init_type(init_typeSEXP);
    Rcpp::traits::input_parameter< const bool >::type bootstrap_positive(bootstrap_positiveSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(sgns_train_cpp(i_indices, j_indices, x_values, n_words, n_contexts, n_dims, n_neg, lr, n_iterations, batch_size, smoothing, reject_positives, init_type, bootstrap_positive, seed, verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wordembeddings_fcm_cpp", (DL_FUNC) &_wordembeddings_fcm_cpp, 13},
    {"_wordembeddings_sgns_train_cpp", (DL_FUNC) &_wordembeddings_sgns_train_cpp, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_wordembeddings(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
