// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fcm_cpp
List fcm_cpp(List tokens_list, NumericVector type_widths_r, LogicalVector keep_types_r, double window_size, NumericVector weights_vec_r, int weights_mode, bool include_target, std::string decay_type, double decay_param, bool asymmetric, double forward_weight, double backward_weight, bool verbose, int n_threads);
RcppExport SEXP _wordembeddings_fcm_cpp(SEXP tokens_listSEXP, SEXP type_widths_rSEXP, SEXP keep_types_rSEXP, SEXP window_sizeSEXP, SEXP weights_vec_rSEXP, SEXP weights_modeSEXP, SEXP include_targetSEXP, SEXP decay_typeSEXP, SEXP decay_paramSEXP, SEXP asymmetricSEXP, SEXP forward_weightSEXP, SEXP backward_weightSEXP, SEXP verboseSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type tokens_list(tokens_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type type_widths_r(type_widths_rSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type keep_types_r(keep_types_rSEXP);
    Rcpp::traits::input_parameter< double >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights_vec_r(weights_vec_rSEXP);
    Rcpp::traits::input_parameter< int >::type weights_mode(weights_modeSEXP);
    Rcpp::traits::input_parameter< bool >::type include_target(include_targetSEXP);
    Rcpp::traits::input_parameter< std::string >::type decay_type(decay_typeSEXP);
    Rcpp::traits::input_parameter< double >::type decay_param(decay_paramSEXP);
    Rcpp::traits::input_parameter< bool >::type asymmetric(asymmetricSEXP);
    Rcpp::traits::input_parameter< double >::type forward_weight(forward_weightSEXP);
    Rcpp::traits::input_parameter< double >::type backward_weight(backward_weightSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fcm_cpp(tokens_list, type_widths_r, keep_types_r, window_size, weights_vec_r, weights_mode, include_target, decay_type, decay_param, asymmetric, forward_weight, backward_weight, verbose, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// sgns_streaming_cpp
List sgns_streaming_cpp(const List& tokens_list, const int min_count, const int vocab_size, const double vocab_coverage, const CharacterVector& vocab_keep, const NumericVector& type_widths, const int n_dims, const int n_neg, const int window, const double lr, const int epochs, const double context_smoothing, const double subsample, const std::string weights_type, const double weights_alpha, const NumericVector& weights_vec, const int weights_mode, const bool include_target, const double forward_weight, const double backward_weight, const std::string init_type, const int seed, const bool verbose, const int threads);
RcppExport SEXP _wordembeddings_sgns_streaming_cpp(SEXP tokens_listSEXP, SEXP min_countSEXP, SEXP vocab_sizeSEXP, SEXP vocab_coverageSEXP, SEXP vocab_keepSEXP, SEXP type_widthsSEXP, SEXP n_dimsSEXP, SEXP n_negSEXP, SEXP windowSEXP, SEXP lrSEXP, SEXP epochsSEXP, SEXP context_smoothingSEXP, SEXP subsampleSEXP, SEXP weights_typeSEXP, SEXP weights_alphaSEXP, SEXP weights_vecSEXP, SEXP weights_modeSEXP, SEXP include_targetSEXP, SEXP forward_weightSEXP, SEXP backward_weightSEXP, SEXP init_typeSEXP, SEXP seedSEXP, SEXP verboseSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type tokens_list(tokens_listSEXP);
    Rcpp::traits::input_parameter< const int >::type min_count(min_countSEXP);
    Rcpp::traits::input_parameter< const int >::type vocab_size(vocab_sizeSEXP);
    Rcpp::traits::input_parameter< const double >::type vocab_coverage(vocab_coverageSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type vocab_keep(vocab_keepSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type type_widths(type_widthsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_dims(n_dimsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_neg(n_negSEXP);
    Rcpp::traits::input_parameter< const int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< const double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< const int >::type epochs(epochsSEXP);
    Rcpp::traits::input_parameter< const double >::type context_smoothing(context_smoothingSEXP);
    Rcpp::traits::input_parameter< const double >::type subsample(subsampleSEXP);
    Rcpp::traits::input_parameter< const std::string >::type weights_type(weights_typeSEXP);
    Rcpp::traits::input_parameter< const double >::type weights_alpha(weights_alphaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type weights_vec(weights_vecSEXP);
    Rcpp::traits::input_parameter< const int >::type weights_mode(weights_modeSEXP);
    Rcpp::traits::input_parameter< const bool >::type include_target(include_targetSEXP);
    Rcpp::traits::input_parameter< const double >::type forward_weight(forward_weightSEXP);
    Rcpp::traits::input_parameter< const double >::type backward_weight(backward_weightSEXP);
    Rcpp::traits::input_parameter< const std::string >::type init_type(init_typeSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sgns_streaming_cpp(tokens_list, min_count, vocab_size, vocab_coverage, vocab_keep, type_widths, n_dims, n_neg, window, lr, epochs, context_smoothing, subsample, weights_type, weights_alpha, weights_vec, weights_mode, include_target, forward_weight, backward_weight, init_type, seed, verbose, threads));
    return rcpp_result_gen;
END_RCPP
}
// sgns_from_fcm_cpp
List sgns_from_fcm_cpp(const IntegerVector& i_indices, const IntegerVector& j_indices, const NumericVector& x_values, const int n_words, const int n_contexts, const int n_dims, const int n_neg, const double lr, const int epochs, const std::string init_type, const int seed, const bool verbose, const int threads);
RcppExport SEXP _wordembeddings_sgns_from_fcm_cpp(SEXP i_indicesSEXP, SEXP j_indicesSEXP, SEXP x_valuesSEXP, SEXP n_wordsSEXP, SEXP n_contextsSEXP, SEXP n_dimsSEXP, SEXP n_negSEXP, SEXP lrSEXP, SEXP epochsSEXP, SEXP init_typeSEXP, SEXP seedSEXP, SEXP verboseSEXP, SEXP threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type i_indices(i_indicesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type j_indices(j_indicesSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type x_values(x_valuesSEXP);
    Rcpp::traits::input_parameter< const int >::type n_words(n_wordsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_contexts(n_contextsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_dims(n_dimsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_neg(n_negSEXP);
    Rcpp::traits::input_parameter< const double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< const int >::type epochs(epochsSEXP);
    Rcpp::traits::input_parameter< const std::string >::type init_type(init_typeSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const int >::type threads(threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(sgns_from_fcm_cpp(i_indices, j_indices, x_values, n_words, n_contexts, n_dims, n_neg, lr, epochs, init_type, seed, verbose, threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_wordembeddings_fcm_cpp", (DL_FUNC) &_wordembeddings_fcm_cpp, 14},
    {"_wordembeddings_sgns_streaming_cpp", (DL_FUNC) &_wordembeddings_sgns_streaming_cpp, 24},
    {"_wordembeddings_sgns_from_fcm_cpp", (DL_FUNC) &_wordembeddings_sgns_from_fcm_cpp, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_wordembeddings(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
