# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fcm_cpp <- function(tokens_list, type_widths, keep_types, window_size, weights_vec, weights_mode, include_target, decay_type, decay_param, asymmetric, forward_weight, backward_weight, verbose) {
    .Call(`_wordembeddings_fcm_cpp`, tokens_list, type_widths, keep_types, window_size, weights_vec, weights_mode, include_target, decay_type, decay_param, asymmetric, forward_weight, backward_weight, verbose)
}

sgns_train_cpp <- function(i_indices, j_indices, x_values, n_words, n_contexts, n_dims, n_neg, lr, n_iterations, batch_size, smoothing, reject_positives, init_type, bootstrap_positive, seed, verbose) {
    .Call(`_wordembeddings_sgns_train_cpp`, i_indices, j_indices, x_values, n_words, n_contexts, n_dims, n_neg, lr, n_iterations, batch_size, smoothing, reject_positives, init_type, bootstrap_positive, seed, verbose)
}

